### PR TITLE
fuel economy dataset

### PR DESCRIPTION
**Pull request by bkmgit**
Can possibly also expand names, for example cty -> city, hwy -> highway, but currently left as is to be consistent with the source dataset

### CODE REVIEW

**Comment by bkmgit** [comment]
https://github.com/red-data-tools/red-datasets/issues/115

**Comment by bkmgit** [comment]
@kou review would be helpful

**Comment by kou** [comment]
Sorry for my late work!
I'll merge this once CI is passed.

**Comment by bkmgit** [comment]
Thanks for the fixes.

**Comment by kou** [comment]
Merged.
Thanks!

**Pull request merged**
